### ISSUE TITLE
Question regarding porting

### ISSUE THREAD

**Issue by ntzrmtthihu777** [pepe2k/u-boot_mod#149]
Greets.

Been working on adding Senao/EnGenius ENS202EXT support to this repo, was
looking at lines 132-140 in u-boot/include/configs/db12x.h, and wondering how
these values were calculated. I assume its an offset from the start of flash (which
is 0x9f000000, right?), but calculating that based on the mtdparts and CFG_ENV_*
for the yuncore cpe870 doesn't quite match up.

**Comment by pepe2k** [comment]
Hi @ntzrmtthihu777,

> Been working on adding Senao/EnGenius ENS202EXT support to this repo, was
> looking at lines 132-140 in u-boot/include/configs/db12x.h, and wondering how
> these values were calculated. I assume its an offset from the start of flash (which
> is 0x9f000000, right?), but calculating that based on the mtdparts and CFG_ENV_*
> for the yuncore cpe870 doesn't quite match up.

I took original CONFIG_BOOTARGS/bootargs environment value from the vendor U-Boot (and this is my general approach when adding support for new board).

In most cases (for majority of boards in ar71xx/generic subtarget), if you use OpenWrt/LEDE, you don't need to think about proper bootargs definition as, even if these values are passed correctly to the kernel, they are/will be ignored anyway (because of a bug/mistake in [image command line hack patch](https://github.com/lede-project/source/blob/master/target/linux/ar71xx/patches-4.4/508-MIPS-ath79-prom-image-command-line-hack.patch)... I plan to fix that sooner or later).
