### ISSUE TITLE
Wrong image in your server

### ISSUE THREAD

**Issue by f-r-i-t-z** [pepe2k/u-boot_mod#175]
Ok. Maybe Who is wrong its me and yet I need to understand.
Your server image for example 
" u-boot_mod__tp-link_tl-wr740n_v4__20170812__git_master-1fb9cda8.bin 123.00 KB 2017-08-12 02:56:40"

123.00 KiB When?

"TP-Link TL-WR740N v4 | AR9331 | 4 MiB | 32 MiB DDR1 | 64 KiB, LZMA | RO"

Was supposed to be 64Kib?

Just wondering to not make some wrong flash..
Thank you for your wonderful work.

**Comment by pepe2k** [comment]
Hello @f-r-i-t-z,

For (most) TP-Link devices, I changed flash organization, so that the bigger U-Boot image (ready images are bigger than 64 KB) and writable environment could fit in `u-boot` mtd partition. Please, have a look at this table:
![mr3020_u-boot-modification_flash-map_comparison](https://user-images.githubusercontent.com/2934612/29492794-9356aa98-8587-11e7-8a2c-04162154cd2e.png)

Because of the MAC address, WPS pin and HW ID which are usually stored in second 64 KB block, you should first make a copy of first two 64 KB blocks from your FLASH, then combine it with selected image and finally write back 128 KB to FLASH.

There is a dedicated script which automates this process: https://github.com/pepe2k/u-boot_mod/blob/master/target_util/u-boot-upgrade

Cheers,
Piotr
