### ISSUE TITLE
Add support for skylab SKW71 ar9331 module.

### ISSUE THREAD

**Issue by Kenzu** [pepe2k/u-boot_mod#37]
Hey

How do I add support for this module?
I have a PDF with spec and pinout.
Have 3 modules to test with.
They have 64MB ram and 8MB flash, but have new 16MB chips I want to put on.

Se this for PDF https://drive.google.com/file/d/0Bxi31Nhfkw_sZ3FHZ2JDN3NPSTAzemJReWdYSHc5SHluOElZ/edit?usp=sharing

Thanks

Jesper

**Comment by ondonadas** [comment]
Hi guys

Recently I buy one of those pieces skylab SKW71 (based on ar9331). The product comes preloaded with uboot and rootfs (openwrt), but without any support (neither uboot nor kernel source code from manufacturer).

Did you make any progress on it?
Which will be the first approach in order to configure uboot and kernel source code?

Thanks in advance

Sergios
